name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - develop

jobs:

  Integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js environment
      uses: actions/setup-node@v6.3.0
      with:
        node-version: '22.12'
        cache: 'npm'
    - name: Install angular CLI
      run: npm install -g @angular/cli
      
    - name: Compile the frotnend app
      run: npm install     

    - name: Execute the unit test cases
      run: npm run test

    - name: Execute the npm build
      run: npm run build

    - name: check the output files
      run: ls -lart ${{ vars.application_path }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: App-output
        path: dist

  Deployment:
    runs-on: ubuntu-22.04
    needs: Integration
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: App-output

    - name: check the files
      run: |
        ls -lart
        ls -lart jaiapp/browser/

    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_MUD_099819200 }}
        repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
        action: "upload"
        app_location: "jaiapp/browser"
        skip_app_build: true
        
