# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: agent1

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v6.3.0

    - name: Compile the frotnend app
      run: npm install

    - name: Execute the unit test cases
      run: npm run test

    - name: Execute the npm build
      run: npm run build

    - name: check the output files
      run: ls -lart dist/

    #- name: Add VM to known_hosts
      #run: |
        #mkdir -p ~/.ssh
        #ssh-keyscan -H 20.41.217.50 >> ~/.ssh/known_hosts  

    - name: SSH-SCP-SSH Pipeline
      uses: kangketikonlen/ssh-pipeline@v0.0.3
      with:
        host: 20.41.217.50
        port: 22
        user: azadmin
        pass: Azadmin@2026@#
        scp: dist/jaiapp/browser/* /var/www/html/
       

                  
